import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { format } from "date-fns";

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: "Helvetica" },
  title: { fontSize: 22, marginBottom: 6, fontFamily: "Helvetica-Bold" },
  subtitle: { fontSize: 11, color: "#666", marginBottom: 3 },
  section: { marginTop: 16 },
  sectionTitle: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
    color: "#1a1a2e",
  },
  body: { fontSize: 10, lineHeight: 1.5, marginBottom: 3 },
  bullet: { fontSize: 10, marginLeft: 12, marginBottom: 2 },
  divider: { borderBottom: "1 solid #e0e0e0", marginVertical: 12 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
  },
});

export default function MeetingPdfDocument({ booking }) {
  const { event, recordings, name, email, startTime, endTime, meetLink } =
    booking;
  const latest = recordings?.[0];

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{event.title}</Text>
        <Text style={styles.subtitle}>
          {format(new Date(startTime), "MMMM d, yyyy")} —{" "}
          {format(new Date(startTime), "h:mm a")} to{" "}
          {format(new Date(endTime), "h:mm a")}
        </Text>
        {meetLink && <Text style={styles.subtitle}>Meet: {meetLink}</Text>}

        <View style={styles.divider} />

        <Text style={styles.sectionTitle}>Participants</Text>
        <Text style={styles.body}>
          Booked by: {name} ({email})
        </Text>
        <Text style={styles.body}>Host: {event.user.name}</Text>

        {latest?.summary && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>AI Summary</Text>
            <Text style={styles.body}>{latest.summary.summary}</Text>

            {latest.summary.keyPoints?.length > 0 && (
              <>
                <Text style={[styles.sectionTitle, { marginTop: 10 }]}>
                  Key Points
                </Text>
                {latest.summary.keyPoints.map((p, i) => (
                  <Text key={i} style={styles.bullet}>
                    {"\u2022"} {p}
                  </Text>
                ))}
              </>
            )}

            {latest.summary.actionItems?.length > 0 && (
              <>
                <Text style={[styles.sectionTitle, { marginTop: 10 }]}>
                  Action Items
                </Text>
                {latest.summary.actionItems.map((a, i) => (
                  <Text key={i} style={styles.bullet}>
                    {"\u2610"} {a}
                  </Text>
                ))}
              </>
            )}

            {latest.summary.followUps?.length > 0 && (
              <>
                <Text style={[styles.sectionTitle, { marginTop: 10 }]}>
                  Follow-ups
                </Text>
                {latest.summary.followUps.map((f, i) => (
                  <Text key={i} style={styles.bullet}>
                    {"\u2022"} {f}
                  </Text>
                ))}
              </>
            )}
          </>
        )}

        {latest?.transcript && (
          <>
            <View style={styles.divider} />
            <Text style={styles.sectionTitle}>Full Transcript</Text>
            <Text style={[styles.body, { fontSize: 8, lineHeight: 1.4 }]}>
              {latest.transcript.transcript}
            </Text>
          </>
        )}

        {!latest && (
          <>
            <View style={styles.divider} />
            <Text style={styles.body}>
              No recording or transcript available for this meeting.
            </Text>
          </>
        )}

        <Text style={styles.footer}>
          Generated by Meet on {format(new Date(), "MMMM d, yyyy")}
        </Text>
      </Page>
    </Document>
  );
}
